name: appMovil CI/CD Workflow

on:
  push:
    branches:
      - master
      - development 
  pull_request:
    branches:
      - master
      - development  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' 

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build application
        run: flutter build apk

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Versión necesaria para Jest y Cypress/Puppeteer

      - name: Install Jest and run unit tests
        run: |
          npm install
          npm run test -- --coverage # Ejecuta Jest y genera reporte de cobertura
        env:
          CI: true

      - name: Store Jest coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage-report
          path: coverage/ # Subir reporte de cobertura de Jest

      # Configuración opcional para Cypress o Puppeteer (pruebas E2E)
      - name: Run Cypress tests
        run: |
          npm install cypress
          npx cypress run
        env:
          CI: true

    env:
      FLUTTER_CHANNEL: stable
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
