name: appMovil CI/CD Workflow

on:
  push:
    branches:
      - master
      - development 
  pull_request:
    branches:
      - master
      - development  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' 

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache 
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Install dependencies
        run: flutter pub get

      # Etapa de Pruebas Unitarias
      - name: Run unit tests
        run: flutter test test/unit_tests/

      # Etapa de Pruebas de Integración
      - name: Run integration tests
        run: flutter test integration_test/

      - name: Build application
        run: flutter build apk

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

    env:
      FLUTTER_CHANNEL: stable
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
